export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURENT_USER";


export const GET_STAFF_DETAILS = "GET_STAFF_DETAILS";
export const ENABLE_STAFF_LOADING = "ENABLE_STAFF_LOADING";
export const DISABLE_STAFF_LOADING = "DISABLE_STAFF_LOADING";

